-- Ensure already-migrated databases contain the Clinical IB blueprint rows.
-- The original seed now includes these rows; this forward migration fixes
-- environments where the seed had already run before the correction.

WITH source(slug, exam_level, major_content_area, percentage_weight, competency_section, applied_knowledge_statement, cognitive_level_guidance, official_blueprint_text, sample_style_guidance, display_order) AS (
  VALUES
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Protecting and enhancing client/client system self- determination (e.g., medication, medical treatment, counseling, placement, right to refuse services)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Protecting and enhancing client/client system self- determination (e.g., medication, medical treatment, counseling, placement, right to refuse services)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 229),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Professional boundaries in the social worker- client/client system relationship (e.g., power differences, influence, privilege, conflicts of interest, self- disclosure, dual relationships)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Professional boundaries in the social worker- client/client system relationship (e.g., power differences, influence, privilege, conflicts of interest, self- disclosure, dual relationships)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 230),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Legal and ethical issues regarding mandatory reporting (e.g., abuse, threat of harm, impaired professionals, duty to warn)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Legal and ethical issues regarding mandatory reporting (e.g., abuse, threat of harm, impaired professionals, duty to warn)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 231),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Legal and ethical issues regarding documentation (e.g., maintaining client records)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Legal and ethical issues regarding documentation (e.g., maintaining client records)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 232),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Responsible billing practices (e.g., managed care, insurance reimbursement, incident to billing)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Responsible billing practices (e.g., managed care, insurance reimbursement, incident to billing)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 233),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Legal and ethical issues related to death and dying', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Legal and ethical issues related to death and dying', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 234),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Ethical issues in supervision and management', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Ethical issues in supervision and management', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 235),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Impact of governmental policies on service delivery (e.g., local, state, federal legislation and policy)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Impact of governmental policies on service delivery (e.g., local, state, federal legislation and policy)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 236),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Legal and ethical issues regarding termination', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Legal and ethical issues regarding termination', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 237),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Ethical issues related to electronic practice', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Ethical issues related to electronic practice', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 238),
  ('lcsw', 'lcsw_clinical', 'I. VALUES AND ETHICS', 36, 'IB. ETHICAL SERVICE DELIVERY', 'Research ethics (e.g., institutional review boards, use of human subjects, informed consent)', 'LCSW/Clinical: emphasize vignette-based reasoning, clinical judgment, assessment, DSM-informed diagnosis, risk assessment, treatment planning, clinical intervention, ethics, confidentiality, boundaries, mandated reporting, supervision, and professional decision-making.', 'I. VALUES AND ETHICS (36%) > IB. ETHICAL SERVICE DELIVERY > Research ethics (e.g., institutional review boards, use of human subjects, informed consent)', 'Use ASWB-style multiple-choice construction with one clear best answer and plausible distractors. Questions may have three or four options in ASWB style, but PrepCzar stores four options, so generate exactly four. Do not use all of the above, none of the above, or both A and B. Use simple wording, avoid trick questions, and keep content relevant to competent social work practice. Use BEST, FIRST, NEXT, or MOST qualifiers when they improve decision-making clarity. Include rationales explaining why the keyed answer is best and why each distractor is less appropriate.', 239)
)
INSERT INTO social_work_blueprint_items (
  exam_track_id,
  topic_id,
  exam_level,
  major_content_area,
  percentage_weight,
  competency_section,
  applied_knowledge_statement,
  cognitive_level_guidance,
  official_blueprint_text,
  sample_style_guidance,
  display_order
)
SELECT
  et.id,
  topics.id,
  source.exam_level,
  source.major_content_area,
  source.percentage_weight,
  source.competency_section,
  source.applied_knowledge_statement,
  source.cognitive_level_guidance,
  source.official_blueprint_text,
  source.sample_style_guidance,
  source.display_order
FROM source
JOIN exam_tracks et ON et.slug = source.slug
LEFT JOIN topics ON topics.exam_track_id = et.id AND topics.title = source.major_content_area
ON CONFLICT (exam_track_id, major_content_area, competency_section, applied_knowledge_statement)
DO UPDATE SET
  topic_id = EXCLUDED.topic_id,
  exam_level = EXCLUDED.exam_level,
  percentage_weight = EXCLUDED.percentage_weight,
  cognitive_level_guidance = EXCLUDED.cognitive_level_guidance,
  official_blueprint_text = EXCLUDED.official_blueprint_text,
  sample_style_guidance = EXCLUDED.sample_style_guidance,
  display_order = EXCLUDED.display_order;
